# Generated by Django 3.2 on 2021-06-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_auto_20210622_2344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_organiser',
        ),
        migrations.AddField(
            model_name='user',
            name='is_organisor',
            field=models.BooleanField(default=True),
        ),
    ]
